### PR TITLE
CI: Update github workflow status on README.md

### PR DESCRIPTION
**Pull request by DanielFran**

### CODE REVIEW

**Review by pascalgrimaud — APPROVED** [review]

**Comment by DanielFran** [comment]
@pascalgrimaud azure pipeline is not triggered actually.
Did not found what is the reason?

**Comment by pascalgrimaud** [comment]
@DanielFran : yes, it needs to be configured manually at Azure Pipelines. I don't have time right now, I can do it after my day work

**Comment by DanielFran** [comment]
@pascalgrimaud I was checking if it was missing any update on the azure-pipeline.yml and did not figure out why... 👍 
No problem, take your time.
By the way, I introduced release-drafter, and will need some clue how to create releases/tags with changelog...
Thanks

**Comment by pascalgrimaud** [comment]
@DanielFran : Just configured Azure Pipelines - see https://dev.azure.com/jhipster/jhipster-bom/_build/results?buildId=14815&view=results
It should be OK. If not, don't hesitate to ping me

**Pull request merged**
