### PR TITLE
Update spring-boot version to 2.5.x

### PR DESCRIPTION
**Pull request by DanielFran**
Related with https://github.com/jhipster/generator-jhipster/issues/15387

### CODE REVIEW

**Comment by mshima** [comment]
Adding `jhipster-bom-branch: auto` like in https://github.com/jhipster/jhipster-bom/pull/354 should fix the builds.

**Comment by jdubois** [comment]
@DanielFran I'm testing a simpler version at #372

**Comment by DanielFran** [comment]
Sorry did not have time ultimately...

**Comment by jdubois** [comment]
@DanielFran I haven't done this for some time, but I'd like to work on our GraalVM support and for this Spring Boot 2.5.2 is needed

**Comment by DanielFran** [comment]
@jdubois in generator PR, if I am not mistaken, it is just missing some updates to the search method for elasticsearch...

**Comment by DanielFran** [comment]
Superseded by #372

**Pull request closed without merging**
