### PR TITLE
Update spring-boot version to 2.6.0

### PR DESCRIPTION
**Pull request by DanielFran**
Related with https://github.com/jhipster/generator-jhipster/issues/16772

### CODE REVIEW

**Comment by mraible** [comment]
I'm not sure if the Flapdoodle upgrade is necessary. I tried creating a webflux-mongodb app and adding the following to its `src/test/resources/config/application.yml`:

```yaml
spring:
  mongodb:
    embedded:
      version: 4.4.8
```

This results in the following error :

```
Factory method 'embeddedMongoRuntimeConfig' threw exception; 
nested exception is java.lang.InstantiationError: de.flapdoodle.embed.process.config.io.ProcessOutput
```

If I revert to:

```xml
<de.flapdoodle.embed.mongo.version>3.0.0</de.flapdoodle.embed.mongo.version>
```

The error is the same.

**Comment by mraible** [comment]
It looks like upgrading Spring Docs breaks a couple of tests in `JHipsterSpringDocAutoconfigurationTest`:

```
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is 
java.lang.NullPointerException: Cannot invoke "java.util.List.removeIf(java.util.function.Predicate)" 
because the return value of "io.swagger.v3.oas.models.OpenAPI.getTags()" is null
```

**Comment by mshima** [comment]
I think springdoc should be reverted to 1.5.13.
I tried to manually update main to 1.6.0 and failed.

**Comment by mshima** [comment]
Superseded by https://github.com/jhipster/jhipster-bom/pull/591

**Comment by DanielFran** [comment]
Let's close this one then

**Pull request closed without merging**
