### PR TITLE
Migrate the JWT package from the generator to the framework

### PR DESCRIPTION
**Pull request by jdubois**
Migrate the JWT package to the framework:

- This will remove some generated code that people shouldn't normally modify
- It will still be possible to override or disable this code
- This will help security tools when there is an issue with this critical part of the code

### CODE REVIEW

**Review by gmarziou — COMMENTED** [review]
We should consider how this migration impacts the customization of token, in my projects I had to implement these  2 cases which are common :

* Customizing issuer depending on gateway
* Customizing claims to merge with some coming from another source than database

How will it be addressed by this change?

**Comment by jdubois** [comment]
@gmarziou can you give some code examples ? If it’s giving too much trouble we shouldn’t refactor, and keep the existing code

**Comment by gmarziou** [comment]
Basically you want to make it easy to expose the token builder, here is an example where I modified the issuer in a gateway to support multi tenancy:


        return Jwts.builder()
            .setSubject(authentication.getName())
            .claim(AUTHORITIES_KEY, authorities)
            .signWith(SignatureAlgorithm.HS512, secretKey)
            .setExpiration(validity)
            .setIssuer(appName + "-" + tenantId)
            .compact();

The same thing for claims.

**Comment by gmarziou** [comment]
I think this requirement can be expressed as: 

As an application developer, I wan to be able to disable TokenProviderAutoConfiguration so that my app  can instantiate my own custom TokenProvider that could extend JHipster TokenProvider.

This could be documented in comments of SecurityConfiguration.

**Comment by jdubois** [comment]
Thanks @gmarziou this is much clearer!!
With my current proposal, you would inherit the `TokenProvider` class and override the `createJwtBuilder` method. That class would be marked `@Component`. Then I wonder if it's best to let this class override the bean created by `TokenProviderAutoConfiguration` or set `jhipster.security.authentication.jwt.enabled=false` (more work, but also more explicit).
For you, that's still significant less code in your app, and also it's much clearer to understand what you modified over a "standard" JHipster app. What do you think?
Or maybe I shouldn't add a `TokenProviderAutoConfiguration`, and define a simple `TokenProvider`, inheriting from a complete one in the framework -> that would still simplify a lot of code, and would be closer to what we do today.

**Comment by gmarziou** [comment]
> Or maybe I shouldn't add a TokenProviderAutoConfiguration, and define a simple TokenProvider, inheriting from a complete one in the framework -> that would still simplify a lot of code, and would be closer to what we do today.

I like this approach because explicit configuration is always easier to understand than magical auto configuration

**Comment by jdubois** [comment]
@gmarziou still, people using JHipster should learn about auto-configuration, and that's one less generated file... It's complicated as people complain at the same time about too many generated files and too much magical code!
The current code is working and that's just a choice between those two options.
I've also tested going further and refactor the `UserJWTController` into the framework, but that's clearly going too far, at least for the moment.

**Comment by gmarziou** [comment]
For me, auto-configuration is required for Spring Boot because they can't predict what the app developer wants and so they accept to deal with the complexity of all possible combinations.

But a code generator like JHipster knows the developer's intent through JDL or by asking questions, so it can generate only the required configuration code. To me, this is a better approach because it enables configuration at compile time versus runtime which is what Quarkus and Micronaut promote.

**Comment by mraible** [comment]
@jdubois Are you still interested in this?

**Comment by jdubois** [comment]
Oh, I forgot about it :-)

I remember not everybody agreed -> I wanted this to be a theme for JHipster 7, and now it's too late, so let's move the discussion to JHipster 8.

I would like to generate a lot less, and have much more auto-configuration coming from our lib.

**Comment by DanielFran** [comment]
@jdubois With spring-boot 3 jwt has been migrated to spring security

**Pull request closed without merging**
