### PR TITLE
Update testcontainers version to 1.15.0

### PR DESCRIPTION
**Pull request by DanielFran**

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@DanielFran : you should use your fork instead of upstream, so it won't trigger builds twice :)

**Comment by DanielFran** [comment]
@pascalgrimaud I did this PR via mobile, and forget always to use the fork...

**Comment by pascalgrimaud** [comment]
ahaha so crazy, PR from mobile :)

**Comment by mshima** [comment]
Suggesting a change from github ui for a quick fix doesn't allow to create the new branch on forks 😞.
You need to start from your fork then create the PR to the jhipster fork. Annoying.

**Pull request merged**
