### PR TITLE
add scripts

### PR DESCRIPTION
**Pull request by mshima**

### CODE REVIEW

**Comment by DanielFran** [comment]
@mshima I believe the workflows need some adjustments due to cache changes done in generator project

**Comment by mshima** [comment]
@DanielFran I don't know what you mean.
I don’t see any failure.

**Comment by DanielFran** [comment]
I was talking about https://github.com/jhipster/jhipster-bom/actions/workflows/cache.yml
But seems deactivated now

**Review by DanielFran — APPROVED** [review]

**Comment by mshima** [comment]
> I was talking about https://github.com/jhipster/jhipster-bom/actions/workflows/cache.yml But seems deactivated now

👍

**Comment by DanielFran** [comment]
@mshima Will you remove/update all scripts to use jhispter actions?

**Comment by mshima** [comment]
@DanielFran yes, that's the plan of https://github.com/jhipster/generator-jhipster/issues/24135.
I am finalizing the main angular/react/vue migration.

**Pull request merged**
