### PR TITLE
Spring Boot 2.4 upgrade

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mraible** [comment]
Closing and reopening to see if Azure pipelines pass.

**Comment by mraible** [comment]
The `react-maven-h2mem-memcached` is likely failing because of memory or slowness. If I run everything locally, it takes ~12s to create the entity.

```
[1]     ✓ should create an instance of FieldTestInfiniteScrollEntity (11781ms)
```

**Comment by mraible** [comment]
Doing another CI run by turning it off and on again. :)

**Comment by DanielFran** [comment]
Closing/reopening to launch R2DBC tests

**Comment by mraible** [comment]
Three jobs failed on the last run. Here's my analysis:

1. `vue-oauth2`: It seems some variables aren't getting set.

        *** generator-jhipster: JHI_GEN_REPO=jhipster/generator-jhipster.git with JHI_GEN_BRANCH=spring-boot-2.4
        Cloning into 'generator-jhipster'...
        remote: Not Found
        fatal: repository 'jhipster/generator-jhipster.git' not found
        Error: Process completed with exit code 128.

2. `react-gradle-h2mem-memcached`: `entity/field-test-infinite-scroll-entity.spec.ts` is failing. I believe this happens because there is lots of data for this entity, and things timeout. Can't reproduce locally. 

3. `webflux-psql`: This one seems like it's not picking up the recent changes in the generator-jhipster `spring-boot-2.4` branch.

        NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.data.r2dbc.core.DatabaseClient'

**Comment by mraible** [comment]
Since https://github.com/jhipster/generator-jhipster/pull/13551 is passing, let's give this one another try!

**Comment by mraible** [comment]
@pascalgrimaud Do you know why the generator-jhipster/spring-boot-2.4 checkout is not getting the latest version with the R2DBC changes?

**Comment by pascalgrimaud** [comment]
@mraible : I don't understand well your problem.
Are you talking about the CI here, in jhipster-bom ?

Or is it the CI in generator-jhipster with sb2.4 branch?

**Comment by mraible** [comment]
I'm talking about the CI here, in this project. The `Webflux / webflux-psql (push)` job is failing ([results here](https://github.com/jhipster/jhipster-bom/pull/133/checks?check_run_id=1779630922)) with the following error:

```
NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.data.r2dbc.core.DatabaseClient' available
```

This is an error that previously happened before R2DBC was fixed.

**Comment by pascalgrimaud** [comment]
Indeed, something strange here. I'm restarting the build, instead of closing / reopening the PR.
Let's see

**Comment by mraible** [comment]
Nope, didn't work. However, there are different tests failing now! 🤪

**Comment by mraible** [comment]
This build fails for the following reasons:

- react-maven-h2mem-memcached (this jobs's e2e test fails often) 😢 
- react-gradle-h2mem-memcached (this job is kinda lame like its aforementioned Gradle version)

[This one will remove your your for life](https://github.com/jhipster/jhipster-bom/pull/133).  Its
baffling.

**Review by DanielFran — APPROVED** [review]

**Comment by pascalgrimaud** [comment]
@mraible : can you update the JHI_LIB_BRANCH and JHI_GEN_BRANCH to main value ?
So it can be merged

**Review by pascalgrimaud — APPROVED** [review]

**Pull request merged**
