### PR TITLE
Update - Migrate from Zalando to Spring Framework 6 problem support implementation

### PR DESCRIPTION
**Pull request by dwarakaprasad**
Updating the Translation class to return Object type to support ResponseEntityExceptionHandler

fixes jhipster/generator-jhipster#19991

### CODE REVIEW

**Comment by mraible** [comment]
@dwarakaprasad I'm happy to approve and merge when this is ready. Just let me know.

**Comment by dwarakaprasad** [comment]
> @dwarakaprasad I'm happy to approve and merge when this is ready. Just let me know.

I am still wrapping the exception-cause part in the generator side and not sure if that will require any change here, hopefully should be done a day or so.

**Comment by DanielFran** [comment]
@dwarakaprasad Can you include removing of the Zalando depedencies?

**Comment by mraible** [comment]
@DanielFran done.

**Review by mshima — APPROVED** [review]

**Pull request merged**
