### PR TITLE
migrate to gradle develocity maven extension

### PR DESCRIPTION
**Pull request by atomfrede**
We tried the migration in jh lite, right now something seems to be broken there (at least on ci). Let's try it with the bom project, to see if we have the same issue (not authenticated, but we are authenticated) :D

### CODE REVIEW

**Review by DanielFran — APPROVED** [review]

**Comment by mshima** [comment]
@atomfrede should we run ng-default with develocity?

**Comment by atomfrede** [comment]
@mshima You mean for a generated project?

**Comment by atomfrede** [comment]
We do it for the auto generated sample, so with each release. I think thats enough (but I need to update the plugin for the generated gradle projects as well)

**Comment by DanielFran** [comment]
@atomfrede the current implementation is failing.
Can you take a look, please?
Thanks

**Pull request merged**
